// @ts-expect-error The app bundle is generated by vercel-build before Vercel typechecks functions.
import app from "../dist/public/app.mjs";

export default function handler(req: any, res: any) {
  if (typeof req.url === "string" && !req.url.startsWith("/api")) {
    req.url = `/api${req.url.startsWith("/") ? "" : "/"}${req.url}`;
  }

  return app(req, res);
}
