// @ts-expect-error The server bundle is generated by vercel-build before Vercel typechecks functions.
import app from "../dist/public/server.mjs";

const API_ROUTE_NAMES = new Set([
  "analytics",
  "auth",
  "backup",
  "callback",
  "cards",
  "collection",
  "customers",
  "dashboard",
  "expenses",
  "export",
  "healthz",
  "images",
  "listing",
  "login",
  "logout",
  "market",
  "pickups",
  "sealed-products",
  "storage",
  "trash",
]);

export default function handler(req: any, res: any) {
  if (typeof req.url === "string" && !req.url.startsWith("/api")) {
    const pathname = req.url.split("?")[0] ?? "/";
    const firstSegment = pathname.replace(/^\/+/, "").split("/")[0] ?? "";
    if (API_ROUTE_NAMES.has(firstSegment)) {
      req.url = `/api${req.url.startsWith("/") ? "" : "/"}${req.url}`;
    }
  }

  return app(req, res);
}
